### ISSUE TITLE
5600x

### ISSUE THREAD

**Issue by DaaNilooo10** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#12]
can i follow the guide to do the same thing on a 5600x?

**Comment by PrimeO7** [comment]
Yes!
But, you most likely won't be able to change the offset too much.
Why do you wanna use this tool for it? Does your motherboard not have any settings to do this already?

This guide is specifically for the 5800X3D, because most Motherboards don't have these settings unlocked in Bios for this CPU.
